#include "main.h"

void intro() {
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____                                             ■" << endl;
	cout << "■                     / ____|                                            ■" << endl;
	cout << "■                    |  |                                                ■" << endl;
	cout << "■                    |  |                                                ■" << endl;
	cout << "■                    |  |___                                             ■" << endl;
	cout << "■                    *______|                                            ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;


	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____                                             ■" << endl;
	cout << "■                     / ____|                                            ■" << endl;
	cout << "■                    |  |       __                                       ■" << endl;
	cout << "■                    |  |     / _`|                                      ■" << endl;
	cout << "■                    |  |___ |(_| |                                      ■" << endl;
	cout << "■                    *______| *___|                                      ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;


	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■                    |  |       __ __| |__                               ■" << endl;
	cout << "■                    |  |     / _`|__  __|                               ■" << endl;
	cout << "■                    |  |___ |(_| |  | |                                 ■" << endl;
	cout << "■                    *______| *___|  |_|                                 ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;

	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■                    |  |       __ __| |__ ,--_---.                      ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;


	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■                    |  |       __ __| |__ ,--_---.                      ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|                                               ■" << endl;
	cout << "■                 | /                                                    ■" << endl;
	cout << "■                 | -----*                                               ■" << endl;
	cout << "■                  `-----| |                                             ■" << endl;
	cout << "■                  |-----| |                                             ■" << endl;
	cout << "■                  |______/                                              ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;


	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■                    |  |       __ __| |__ ,--_---.                      ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|    __                                         ■" << endl;
	cout << "■                 | /        |  |                                        ■" << endl;
	cout << "■                 | -----* |-    -|                                      ■" << endl;
	cout << "■                  `-----| | |  |                                        ■" << endl;
	cout << "■                  |-----| | |  |                                        ■" << endl;
	cout << "■                  |______/  |__|                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;


	Sleep(300);	system("cls");


	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■                    |  |       __ __| |__ ,--_---.                      ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|    __                                         ■" << endl;
	cout << "■                 | /        |  |                                        ■" << endl;
	cout << "■                 | -----* |-    -| ___                                  ■" << endl;
	cout << "■                  `-----| | |  |  / _ *                                 ■" << endl;
	cout << "■                  |-----| | |  | | (_  |                                ■" << endl;
	cout << "■                  |______/  |__|  *___/                                 ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;


	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■                    |  |       __ __| |__ ,--_---.                      ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|    __                                         ■" << endl;
	cout << "■                 | /        |  |                                        ■" << endl;
	cout << "■                 | -----* |-    -| ___   _  __                          ■" << endl;
	cout << "■                  `-----| | |  |  / _ * | |/ /                          ■" << endl;
	cout << "■                  |-----| | |  | | (_  ||  /                            ■" << endl;
	cout << "■                  |______/  |__|  *___/ |_|                             ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;


	Sleep(300);	system("cls");



	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■                    |  |       __ __| |__ ,--_---.                      ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|    __                                         ■" << endl;
	cout << "■                 | /        |  |                                        ■" << endl;
	cout << "■                 | -----* |-    -| ___   _  __ _   _                    ■" << endl;
	cout << "■                  `-----| | |  |  / _ * | |/ /| | | |                   ■" << endl;
	cout << "■                  |-----| | |  | | (_  ||  /  | |_| |                   ■" << endl;
	cout << "■                  |______/  |__|  *___/ |_|   |*__, |                   ■" << endl;
	cout << "■                                                __/ |                   ■" << endl;
	cout << "■                                               |___/                    ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;

	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                   ~                                      ~             ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■                    |  |       __ __| |__ ,--_---.                      ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|    __                                         ■" << endl;
	cout << "■                 | /        |  |                                        ■" << endl;
	cout << "■                 | -----* |-    -| ___   _  __ _   _                    ■" << endl;
	cout << "■                  `-----| | |  |  / _ * | |/ /| | | |                   ■" << endl;
	cout << "■                  |-----| | |  | | (_  ||  /  | |_| |                   ■" << endl;
	cout << "■                  |______/  |__|  *___/ |_|   |*__, |                   ■" << endl;
	cout << "■                                                __/ |                   ■" << endl;
	cout << "■                                               |___/                    ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;

	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                   ~                                      ~             ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■          ~         |  |       __ __| |__ ,--_---.           ~          ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|    __                                         ■" << endl;
	cout << "■                 | /        |  |                                        ■" << endl;
	cout << "■                 | -----* |-    -| ___   _  __ _   _                    ■" << endl;
	cout << "■                  `-----| | |  |  / _ * | |/ /| | | |                   ■" << endl;
	cout << "■                  |-----| | |  | | (_  ||  /  | |_| |                   ■" << endl;
	cout << "■                  |______/  |__|  *___/ |_|   |*__, |                   ■" << endl;
	cout << "■                                                __/ |                   ■" << endl;
	cout << "■                                               |___/                    ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;


	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                   ~                                      ~             ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■          ~         |  |       __ __| |__ ,--_---.           ~          ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|    __                                         ■" << endl;
	cout << "■         ~       | /        |  |                         ~              ■" << endl;
	cout << "■                 | -----* |-    -| ___   _  __ _   _                    ■" << endl;
	cout << "■                  `-----| | |  |  / _ * | |/ /| | | |                   ■" << endl;
	cout << "■                  |-----| | |  | | (_  ||  /  | |_| |                   ■" << endl;
	cout << "■                  |______/  |__|  *___/ |_|   |*__, |                   ■" << endl;
	cout << "■                                                __/ |                   ■" << endl;
	cout << "■                                               |___/                    ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;

	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                   ~                                      ~             ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■          ~         |  |       __ __| |__ ,--_---.           ~          ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|    __                                         ■" << endl;
	cout << "■         ~       | /        |  |                         ~              ■" << endl;
	cout << "■                 | -----* |-    -| ___   _  __ _   _                    ■" << endl;
	cout << "■                  `-----| | |  |  / _ * | |/ /| | | |                   ■" << endl;
	cout << "■                  |-----| | |  | | (_  ||  /  | |_| |                   ■" << endl;
	cout << "■                  |______/  |__|  *___/ |_|   |*__, |                   ■" << endl;
	cout << "■              ~                                 __/ |         ~         ■" << endl;
	cout << "■                                               |___/                    ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;

	Sleep(300);	system("cls");

	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                   ~                                      ~             ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      _____          ___                                ■" << endl;
	cout << "■                     / ____|        / _/                                ■" << endl;
	cout << "■          ~         |  |       __ __| |__ ,--_---.           ~          ■" << endl;
	cout << "■                    |  |     / _`|__  __|/__(  __/                      ■" << endl;
	cout << "■                    |  |___ |(_| |  | |  | |___┌┐                       ■" << endl;
	cout << "■                    *______| *___|  |_|  |_______|                      ■" << endl;
	cout << "■                  / ____|    __                                         ■" << endl;
	cout << "■         ~       | /        |  |                         ~              ■" << endl;
	cout << "■                 | -----* |-    -| ___   _  __ _   _                    ■" << endl;
	cout << "■                  `-----| | |  |  / _ * | |/ /| | | |                   ■" << endl;
	cout << "■                  |-----| | |  | | (_  ||  /  | |_| |                   ■" << endl;
	cout << "■                  |______/  |__|  *___/ |_|   |*__, |                   ■" << endl;
	cout << "■              ~                                 __/ |         ~         ■" << endl;
	cout << "■                                               |___/                    ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■                      ~                   ~                             ■" << endl;
	cout << "■                                                                        ■" << endl;
	cout << "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■" << endl;

	system("cls");
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                안녕하세요! 새로운 점장님이시군요!                          " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	system("pause");

	system("cls");
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	GRAY cout << "                안녕하세요! 새로운 점장님이시군요!                    " << endl;
	cout << "                                                                            " << endl;
	WHITE cout << "                마침 리모델링이 딱 끝났어요!                          " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	system("pause");

	system("cls");
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	GRAY cout << "                안녕하세요! 새로운 점장님이시군요!                    " << endl;
	cout << "                                                                            " << endl;
	cout << "                마침 리모델링이 딱 끝났어요!                          " << endl;
	cout << "                                                                            " << endl;
	WHITE cout << "                제가 누구냐고요? 그러고 보니 제 소개를 안했네요!      " << endl;
	cout << "                저는 점장님의 비서 겸 직원인 냠냠이에요!                    " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	system("pause");

	system("cls");
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	GRAY cout << "                안녕하세요! 새로운 점장님이시군요!                    " << endl;
	cout << "                                                                            " << endl;
	cout << "                마침 리모델링이 딱 끝났어요!                          " << endl;
	cout << "                                                                            " << endl;
	cout << "                제가 누구냐고요? 그러고 보니 제 소개를 안했네요!      " << endl;
	cout << "                저는 점장님의 비서 겸 직원인 냠냠이에요!                    " << endl;
	cout << "                                                                            " << endl;
	WHITE cout << "                제가 점장님을 위해 설명서를 가지고 왔어요!                  " << endl;
	cout << "                                                                            " << endl;
	cout << "                아무 키나 눌러서 설명서를 확인해보세요! :)                  " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	system("pause");

	system("cls");
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                 <설명서>                                                   " << endl;
	cout << "                                                                            " << endl;
	cout << "                 1. 조작은 키보드로만 가능합니다                            " << endl;
	cout << "                 2. 5분은 '일주일'로 계산됩니다                             " << endl;
	cout << "                 3. 누구보다 멋진 카페로 만들어주세요!                      " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                 ...                                                        " << endl;
	cout << "                                                                            " << endl;
	cout << "                 그런데                                                     " << endl;
	cout << "                                                                            " << endl;
	cout << "                 새 점장님과 카페 이름이 뭐였죠?                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;
	cout << "                                                                            " << endl;

	system("pause");
}